config/routes.rb
Rails.application.routes.draw do

  
  get 'home/index'
  get 'home/about'
  get 'home/contact'
  root "home#index"
  devise_for :users do
    resources :mentors
    
  end
  resource :businesses  do
    resources :tasks
  end
  get '/users/:id', to: 'users#show' 
  
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  
   
  
  

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end
 

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/business.rb
class Business < ApplicationRecord
 belongs_to :user


 def to_param
    "#{id}-#{first_name} #{last_name}}".parameterize
  end

end

app/models/mentor.rb
class Mentor < ApplicationRecord
  has_many :users
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :business
 has_many :users, through: :userTasks
end

app/models/user.rb
class User < ApplicationRecord
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable
       has_many :businesses
           def full_name
          self.firstName + " " + self.lastName
        end

       

  end

app/models/user_task.rb
class UserTask < ApplicationRecord
  belongs_to :user
  belongs_to :tasks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
    
   
end

app/controllers/businesses_controller.rb
class BusinessesController < ApplicationController
  before_action :set_business, only: %i[ show edit update destroy ]

  # GET /businesses or /businesses.json
  def index
    @businesses = Business.all
  # GET /businesses/1 or /businesses/1.json
  end
  def show
  end

  # GET /businesses/new
  def new
    @user = User.all
    @business = Business.find(params(id: @user.id))
    
  end

  # GET /businesses/1/edit
  def edit
  end

  # POST /businesses or /businesses.json
  def create
    @business = Business.new(business_params)

    respond_to do |format|
      if @business.save
        format.html { redirect_to @business, notice: "Business was successfully created." }
        format.json { render :show, status: :created, location: @business }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @business.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /businesses/1 or /businesses/1.json
  def update
    respond_to do |format|
      if @business.update(business_params)
        format.html { redirect_to @business, notice: "Business was successfully updated." }
        format.json { render :show, status: :ok, location: @business }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @business.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /businesses/1 or /businesses/1.json
  def destroy
    @business.destroy
    respond_to do |format|
      format.html { redirect_to businesses_url, notice: "Business was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_business
      @business = Business.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def business_params
      params.require(:business).permit(:businessName, :description, :location, :owner_id, :user_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end

  def contact
  end
end

app/controllers/mentors_controller.rb
class MentorsController < ApplicationController
  before_action :set_mentor, only: %i[ show edit update destroy ]

  # GET /mentors or /mentors.json
  def index
    @mentors = Mentor.all
  end

  # GET /mentors/1 or /mentors/1.json
  def show
  end

  # GET /mentors/new
  def new
    @mentor = Mentor.new
  end

  # GET /mentors/1/edit
  def edit
  end

  # POST /mentors or /mentors.json
  def create
    @mentor = Mentor.new(mentor_params)

    respond_to do |format|
      if @mentor.save
        format.html { redirect_to @mentor, notice: "Mentor was successfully created." }
        format.json { render :show, status: :created, location: @mentor }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @mentor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mentors/1 or /mentors/1.json
  def update
    respond_to do |format|
      if @mentor.update(mentor_params)
        format.html { redirect_to @mentor, notice: "Mentor was successfully updated." }
        format.json { render :show, status: :ok, location: @mentor }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @mentor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mentors/1 or /mentors/1.json
  def destroy
    @mentor.destroy
    respond_to do |format|
      format.html { redirect_to mentors_url, notice: "Mentor was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mentor
      @mentor = Mentor.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def mentor_params
      params.require(:mentor).permit(:user_id, :descritpion)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: %i[ show edit update destroy ]

  # GET /tasks or /tasks.json
  def index
    @tasks = Task.all
  end

  # GET /tasks/1 or /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks or /tasks.json
  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: "Task was successfully created." }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1 or /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: "Task was successfully updated." }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1 or /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: "Task was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def task_params
      params.require(:task).permit(:taskName, :description, :startDate, :endDate, :business_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    
    def show
        @user = User.find(params[:id])
       @businesses = @user.businesses
    end
    
    
end

app/helpers/application_helper.rb
module ApplicationHelper

    def full_name(user)
        user.firstName + " " + user.lastName
    end
end

app/helpers/businesses_helper.rb
module BusinessesHelper

    prepend  UsersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/mentors_helper.rb
module MentorsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
    def full_name(user)
        user.firstName + " " + user.lastName
    end

end

app/views/businesses/_form.html.erb
<div class="container">
<div class="row">
<div class="col s12">
<%= simple_form_for @business do |form| %>
  <% if business.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(business.errors.count, "error") %> prohibited this business from being saved:</h2>

      <ul>
        <% business.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %> 
      </ul>
    </div>
  <% end %>

<div class="input-field col m10">
<%= form.association :user, collection: @user, label_method: :full_name, value_method: :id%>
  <div class="input-field col m10">
   
    <%= form.input:businessName %>
   
  </div>

  <div class="input-field col m10"> 
    <%= form.input :description, as: :text, :input_html=>{class: "materialize-textarea", :cols => 5, :rows => 10} %>
  </div>

  <div class="input-field col m10">
  
    <%= form.input :location %>
  </div>

  <div class="input-field col m10">
   
    <%= form.input :owner_id %>
  </div>

  <div class="actions col m10">
    <%= form.submit  class: "wave-effect btn-flat"%>
  </div>
<% end %>
</div>
</div>
</div>

app/views/businesses/edit.html.erb
<h1>Editing Business</h1>

<%= render 'form', business: @business %>

<%= link_to 'Show', @business %> |
<%= link_to 'Back', businesses_path %>

app/views/businesses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Businesses</h1>

<table>
  <thead>
    <tr>
      <th>Businessname</th>
      <th>Description</th>
      <th>Location</th>
      <th>Owner</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @businesses.each do |business| %>
      <tr>
        <td><%= business.businessName %></td>
        <td><%= business.description %></td>
        <td><%= business.location %></td>
        <td><%= business.owner_id %></td>
        <td><%= link_to 'Show', business %></td>
      
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/businesses/new.html.erb
<div class="container">
    <h1>New Business</h1>


<%= render 'form', business: @business %>

<%= link_to 'Back', businesses_path %>
</div>

app/views/businesses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Businessname:</strong>
  <%= @business.businessName %>
</p>

<p>
  <strong>Description:</strong>
  <%= @business.description %>
</p>

<p>
  <strong>Location:</strong>
  <%= @business.location %>
</p>

<p>
  <strong>Owner:</strong>
  <%= @business.owner_id %>
</p>


<%= link_to 'Back', businesses_path %>

app/views/home/about.html.erb
<h1>Home#about</h1>
<p>Find me in app/views/home/about.html.erb</p>

app/views/home/contact.html.erb
<h1>Home#contact</h1>
<p>Find me in app/views/home/contact.html.erb</p>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/_header.html.erb
<nav>
    <div class="nav-wrapper pink darken-2">
      <a href="#!" class="brand-logo">Kula Girls</a>
      <a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i></a>
      <ul class="right hide-on-med-and-down">
        <li> <%=link_to "Home", root_path %></li>
        <li> <%=link_to "Business List", businesses_path %></li>
        
        <%if current_user%>
            <li><%= link_to "Sign Out", destroy_user_session_path, :method => :delete  %> </li>
            <li><%= link_to full_name(current_user) ,root_path %></li>
        <%else%>
            <li><%= link_to "Sign In", new_user_session_url %> </li>
            <%end%>
      </ul>
    </div>
  </nav>

  <ul class="sidenav" id="mobile-demo">
    <li> <%=link_to "Home", root_path %></li>
        <li> <%=link_to "Businesses", businesses_path %></li>
        
        <%if current_user%>
            <li><%= link_to "Sign Out", destroy_user_session_path, :method => :delete  %> </li>
            <li><%= link_to full_name(current_user) ,root_path %></li>
        <%else%>
            <li><%= link_to "Sign In", new_user_session_url %> </li>
            <%end%>
  </ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

    <title>BlackWidow</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  
    <%= render './layouts/header/' %>
    <div class="container">
    <%= yield %>
    </div>
  </body>
</html>
s

app/views/mentors/_form.html.erb
<div class="container">
<div class="row">
<div class="col s12">
<%= simple_form_for @mentor do |form| %>
  <% if mentor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(mentor.errors.count, "error") %> prohibited this mentor from being saved:</h2>

      <ul>
        <% mentor.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="input-field col s10  ">
    <%= form.label "Select User" %>
<%= form.association :user, collection: @user, label_method: :full_name, value_method: :id%>
  </div>
  <div class="input-field col s10  ">
    <%= form.text_area :descritpion%>
    <%= form.label :descritpion %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
</div>
</div>
</div>

app/views/mentors/edit.html.erb
<h1>Editing Mentor</h1>

<%= render 'form', mentor: @mentor %>

<%= link_to 'Show', @mentor %> |
<%= link_to 'Back', mentors_path %>

app/views/mentors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Mentors</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Descritpion</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @mentors.each do |mentor| %>
      <tr>
        <td><%= mentor.user_id %></td>
        <td><%= mentor.descritpion %></td>
        <td><%= link_to 'Show', mentor %></td>
        <td><%= link_to 'Edit', edit_mentor_path(mentor) %></td>
        <td><%= link_to 'Destroy', mentor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Mentor', new_mentor_path %>

app/views/mentors/new.html.erb
<h1>New Mentor</h1>

<%= render 'form', mentor: @mentor %>

<%= link_to 'Back', mentors_path %>

app/views/mentors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @mentor.user_id %>
</p>

<p>
  <strong>Descritpion:</strong>
  <%= @mentor.descritpion %>
</p>

<%= link_to 'Edit', edit_mentor_path(@mentor) %> |
<%= link_to 'Back', mentors_path %>

app/views/tasks/_form.html.erb
<div class="container">
<div class="row">
<div class="col s12">


<%= form_with(model: task) do |form| %>
  <% if task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
        <% task.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="input-field s10">
    <%= form.label :taskName %>
    <%= form.text_field :taskName %>
  </div>

  <div class="input-field s10">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="input-field s10">
    <%= form.label :startDate %>
    <%= form.date_select :startDate %>
  </div>

  <div class="input-field s10">
    <%= form.label :endDate %>
    <%= form.date_select :endDate %>
  </div>

  <div class="input-field s10">
    <%= form.label :business_id %>
    <%= form.text_field :business_id %>
  </div>

  <div class="actions">
    <%= form.submit, class: "waves-effect waves-light btn" %>
  </div>

  
<% end %>

</div>
</div>
</div>

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tasks</h1>

<table>
  <thead>
    <tr>
      <th>Taskname</th>
      <th>Description</th>
      <th>Startdate</th>
      <th>Enddate</th>
      <th>Business</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.taskName %></td>
        <td><%= task.description %></td>
        <td><%= task.startDate %></td>
        <td><%= task.endDate %></td>
        <td><%= task.business_id %></td>
        <td><%= link_to 'Show', task %></td>
        <td><%= link_to 'Edit', edit_task_path(task) %></td>
        <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Taskname:</strong>
  <%= @task.taskName %>
</p>

<p>
  <strong>Description:</strong>
  <%= @task.description %>
</p>

<p>
  <strong>Startdate:</strong>
  <%= @task.startDate %>
</p>

<p>
  <strong>Enddate:</strong>
  <%= @task.endDate %>
</p>

<p>
  <strong>Business:</strong>
  <%= @task.business_id %>
</p>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>

app/views/users/show.html.erb
<%= @user.firstName%>

<% if @mentors %>
  <%= link_to 'Mentor ', user_mentors_path, class:"waves-effect waves-light btn" %>
<% end %>
<% if @businesses%>
    <%link_to Businesses, user_businesses_path%>
<%end%>